### ISSUE TITLE
Build on Windows withOUT Cygwin/MingW?

### ISSUE THREAD

**Issue by cjohn-murphy** [stahta01/cmoc-win32#1]
Noob question, but I can't figure out where to even begin.

Have you successfully built this?
Is there documentation on how to build all of this project on Windows?

**Comment by stahta01** [comment]
I think I built it once years ago.
You might follow the links to here [sarrazip](http://perso.b2b2c.ca/~sarrazip/dev/cmoc.html)

**Comment by cjohn-murphy** [comment]
Thanks. I may have missed the point of cmoc-win32, I thought it removed the requirement for Cygwin/MinGW.
And as far as I know, Pierre's original cmoc won't even run on Windows.
My hope was that somebody had a pure Windows version. I  thought that was cmoc-win32.

thanks for the reply.

John

**Comment by stahta01** [comment]
Cygwin can be replaced by MSys2 in the needs; but, MInGW64 or MInGW is still needed.

Tim S.
